{ config, pkgs, lib, ... }:

{
  home.packages = with pkgs; [
    niri
    xwayland-satellite
    swaybg
  ];

  xdg.configFile."niri/config.kdl" = {
    enable = true;
    text = ''
      // Niri Configuration
      // Generated by Home Manager

      input {
          keyboard {
              xkb {
                  layout "colemak_caws,rulemak_caws"
                  options "caps:backspace,grp:rwin_toggle,lv3:ralt_switch"
              }
          }

          mouse {
              accel-speed -0.8
          }

          focus-follows-mouse
      }

      output "DP-2" {
          mode "2560x1440@500"
          scale 1.0
      }

      layout {
          gaps 10
          center-focused-column "never"

          border {
              width 2
              active-color "#81a1c1"
              inactive-color "#4c566a"
          }

          focus-ring {
              width 2
              active-color "#81a1c1"
              inactive-color "#4c566a"
          }
      }

      prefer-no-csd

      binds {
          Mod+Return { spawn "alacritty"; }
          Mod+A { spawn "fuzzel"; }
          Mod+F { spawn "thunar"; }
          Mod+Tab { show-hotkey-overlay; }

          Mod+Q { close-window; }
          Mod+Shift+Q { close-window; }
          Mod+T { set-window-height "-10%"; }
          Mod+Shift+T { fullscreen-window; }

          Mod+W { focus-column-left; }
          Mod+S { focus-column-right; }
          Mod+R { focus-window-down; }

          Mod+Left { focus-column-left; }
          Mod+Right { focus-column-right; }
          Mod+Up { focus-window-up; }
          Mod+Down { focus-window-down; }

          Mod+1 { focus-workspace 1; }
          Mod+2 { focus-workspace 2; }
          Mod+3 { focus-workspace 3; }
          Mod+4 { focus-workspace 4; }
          Mod+5 { focus-workspace 5; }
          Mod+6 { focus-workspace 6; }
          Mod+7 { focus-workspace 7; }
          Mod+8 { focus-workspace 8; }
          Mod+9 { focus-workspace 9; }
          Mod+0 { focus-workspace 10; }

          Mod+Shift+1 { move-column-to-workspace 1; }
          Mod+Shift+2 { move-column-to-workspace 2; }
          Mod+Shift+3 { move-column-to-workspace 3; }
          Mod+Shift+4 { move-column-to-workspace 4; }
          Mod+Shift+5 { move-column-to-workspace 5; }
          Mod+Shift+6 { move-column-to-workspace 6; }
          Mod+Shift+7 { move-column-to-workspace 7; }
          Mod+Shift+8 { move-column-to-workspace 8; }
          Mod+Shift+9 { move-column-to-workspace 9; }
          Mod+Shift+0 { move-column-to-workspace 10; }

          Mod+Escape { focus-workspace-previous; }

          Mod+Shift+A { spawn "sh" "-c" "grim -g \"$(slurp)\" ~/Pictures/$(date +'%Y%m%d_%H%M%S').png"; }
          Mod+Shift+S { spawn "sh" "-c" "grim -g \"$(slurp)\" - | wl-copy"; }

          XF86AudioRaiseVolume { spawn "wpctl" "set-volume" "@DEFAULT_AUDIO_SINK@" "5%+"; }
          XF86AudioLowerVolume { spawn "wpctl" "set-volume" "@DEFAULT_AUDIO_SINK@" "5%-"; }
          XF86AudioMute { spawn "wpctl" "set-mute" "@DEFAULT_AUDIO_SINK@" "toggle"; }

          // Advanced window management keybindings
          Mod+Comma { move-column-left; }
          Mod+Period { move-column-right; }

          Mod+BracketRight { focus-workspace-down; }
          Mod+BracketLeft { focus-workspace-up; }
          Mod+Shift+BracketLeft { move-column-to-workspace-down; }
          Mod+Shift+BracketRight { move-column-to-workspace-up; }

          Mod+M { switch-preset-column-width; }
          Mod+Shift+M { maximize-column; }

          Mod+N { consume-window-into-column; }
          Mod+Shift+N { expel-window-from-column; }

          Mod+Space { toggle-window-floating; }
      }

      spawn-at-startup "swaybg" "-i" "${config.stylix.image}" "-m" "fill"
      spawn-at-startup "xwayland-satellite"
      spawn-at-startup "waybar"
      spawn-at-startup "dunst"

      animations {
          window-open {
              duration-ms 200
              curve "ease-out-cubic"
          }

          window-close {
              duration-ms 150
              curve "ease-out-cubic"
          }

          workspace-switch {
              duration-ms 250
              curve "ease-out-cubic"
          }
      }

      hotkey-overlay {
          skip-at-startup
      }

    '';
  };
}
